# Change these first
owner: rifqimulyawan # Your GitHub organization or username, where this repository lives
repo: rmmonitor # The name of this repository

sites:
  - name: Rifqi Mulyawan
    url: https://rifqimulyawan.com
  - name: Nadia Aisyah
    url: https://nadiaaisyah.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /rmmonitor
  logoUrl: https://raw.githubusercontent.com/rifqimulyawan/rmmonitor/master/assets/rmmonitor-icon.svg
  name: RMMonitor
  introTitle: "**RMMonitor** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/rifqimulyawan/rmmonitor). No server and databases required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: https://rifqimulyawan.github.io/$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
